# PostgreSQL 설정
services:
  db:
    image: postgres:latest
    container_name: busalimi
    environment:
      POSTGRES_USER: kt
      POSTGRES_PASSWORD: kt123
      POSTGRES_DB: busalimi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: